### ISSUE TITLE
Release 0.17 checklist

### ISSUE THREAD

**Issue by nvie** [liveblocks/liveblocks#303]
### Must haves
- [x] #264 - @GuillaumeSalles 
- [x] #339
- [x] https://github.com/liveblocks/liveblocks.io/pull/257
- [x] Upgrade TLDraw to 0.17, contribute via a PR on that repo - preview: https://github.com/tldraw/tldraw/compare/main...nvie:upgrade-liveblocks?expand=1
  - [x] Undo some of the unnecessary changes in there
  - [x] Make PR for TLDraw + Link to the Upgrade Guide
  - [x] Prepare a message for discord
- [x] #358 - @GuillaumeSalles 
- [x] #337
  - [x] #351 - Chris
  - [x] Convert the React Native example to 0.17 - see https://github.com/liveblocks/liveblocks/pull/329#discussion_r899654559
  - [x] Update the `liveblocks.config.ts` in all examples to [the new/rich template with comments](https://github.com/liveblocks/liveblocks.io/pull/257#issuecomment-1160140456)
- [x] Upgrade TLDraw to 0.16
- [x] #357
  - [x] Update source code
  - [x] Update all examples/templates
  - [x] Update documentation
- [x] #307
- [x] #309
  - [x] #342
- [x] #291
  - [x] Make `_` type params in there optional, and deprecated
  - [x] #317
  - [x] For all internal APIs, make sure to always explicitly pass type params, i.e. never write `Client` in local code, only ever use `Client<TPresence, TStorage>` internally — always connect all types! - Enforced via 62a8ca481c6381f95c31e21a3630de351650ea1f.
- [x] #318
- [x] #319 (in `client`)
- [x] #321 (in `react`, `redux`, and `zustand`)
- [x] #316
- [x] #324
  - [x] Work on codegen idea for compatibility layer
  - [x] Figure out a nice default way to set up local modules. Decision made: we're going to recommend a default template with boilerplate code to include in every React project using Liveblocks (see [template](https://gist.github.com/nvie/5e718902c51ea7dad93cd6952fe1af03#how-to-migrate))
  - [x] #334
- [x] #315
- [x] #348 
- [x] #349 
- [x] Deprecation documentation message should point to official guide instead of @nvie gist
- [x] Remove all `any`s from `liveblocks-client`'s public APIs
  - [x] #308 
  - [x] #354 
  - [x] #332 
  - [x] [Polyfills on `ClientOptions`](https://github.com/liveblocks/liveblocks/blob/5b51035084be5642a9c2c7d3e2dbeb8d3e55e9e9/packages/liveblocks-client/src/types/index.ts#L288) (and the new ones for React Native) - should we move these into a `polyfills` sub-object? (See https://github.com/liveblocks/liveblocks/pull/284#discussion_r887637545 for context.)
  - [x] #341
- [x] #323 - @GuillaumeSalles 

### Nice to haves
- [ ] #286 
  - [ ] #279 
  - [ ] #280
- [ ] Remove all `any`s from `liveblocks-react`'s public APIs
- [ ] Remove all `any`s from `liveblocks-node`'s public APIs
- [ ] Remove all `any`s from `liveblocks-redux`'s public APIs
- [ ] Remove all `any`s from `liveblocks-zustand`'s public APIs
- [ ] https://github.com/liveblocks/liveblocks.io/issues/259

**Comment by GuillaumeSalles** [comment]
@nvie Added a bunch of tasks to do before the release

**Comment by nvie** [comment]
0.17 is out! 🎉
